# Copyright 2022 Shadow Robot Company Ltd.
#
# This program is free software: you can redistribute it and/or modify it
# under the terms of the GNU General Public License as published by the Free
# Software Foundation version 2 of the License.
#
# This program is distributed in the hope that it will be useful, but WITHOUT
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
# FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for
# more details.
#
# You should have received a copy of the GNU General Public License along
# with this program. If not, see <http://www.gnu.org/licenses/>.

arm_trajectories:
  test_trajectory:
    - joint_angles: [1.704, -1.068, 0.407, -0.745, 1.534, 3.0975]
      interpolate_time: 2
    - joint_angles: [1.633, -1.017, 0.571, -0.725, 1.697, 3.079]
      interpolate_time: 2

hand_trajectories:
  test_trajectory:
    - joint_angles: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
      interpolate_time: 1
    - joint_angles: [0.0, 0.0, 0.0, 0.0, 0.531, 0.443, 0.257, 0.0, 0.310, 0.0, 0.0, 0.0, 0.0, 0.623, 0.659, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
      interpolate_time: 1
    - joint_angles: [0.0, 0.0, 0.0, 0.0, 0.475, 0.499, 0.257, 0.0, 0.310, 0.201, 0.203, 0.0, 0.0, 0.514, 0.768, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
      interpolate_time: 1
    - joint_angles: [0.261, 0.052, 0.591, 0.0, 0.435, 0.539, 0.257, -0.045, 0.310, 0.075, 0.324, 0.0, 0.0, 0.434, 0.848, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
      interpolate_time: 1

arm_and_hand_trajectories:
  test_trajectory:
    - joint_angles: [2.077, -1.062, 0.312, -2.604, 1.561, 4.448, -0.0, -0.0, -0.0, -0.034, -0.0, -0.0, -0.0, 0.03, -0.0, -0.0, -0.0, -0.0, -0.035, -0.0, -0.0, -0.0, 0.033, -0.0, 0.003, -0.014, 0.087, 0.002, 0.008, 0.008]
      interpolate_time: 1

arm_joints_order: [ra_elbow_joint, ra_shoulder_lift_joint, ra_shoulder_pan_joint, ra_wrist_1_joint, ra_wrist_2_joint, ra_wrist_3_joint]
hand_joints_order: [FFJ1, FFJ2, FFJ3, FFJ4, LFJ1, LFJ2, LFJ3, LFJ4, LFJ5, MFJ1, MFJ2, MFJ3, MFJ4, RFJ1, RFJ2, RFJ3, RFJ4, THJ1, THJ2, THJ3, THJ4, THJ5, WRJ1, WRJ2]
