#!/bin/bash -e

check_firmware_from_ip(){
  responded=false
  while read -r cmd; do
    if [[ $cmd =~ "URSoftware" ]]; then
      while read firmware; do
        if [[ $firmware != "" ]]; then
          if [[ $cmd =~ $firmware ]]; then
            echo "UR version $cmd is supported by Shadow"
            responded=true
            break 2
          fi
        fi
      done <../config/known_good_firmware.txt
      echo "UR version $cmd is NOT supported by Shadow. Use our software at your own risk"
      responded=true
      break
    fi
  done < <(echo "polyscopeversion" | nc -w2 $1 29999)

  if [[ $responded == false ]]; then
    echo "UR robot did not respond"
  fi
}

source /opt/ros/kinetic/setup.bash
source ~/projects/shadow_robot/base/devel/setup.bash 
source ~/projects/shadow_robot/base_deps/devel/setup.bash 

arm_config_files=$(rosls sr_ur_arm_config/config/ | grep robot_hw.yaml)
arm_ips=()
for arm in $arm_config_files ; do 
  arm_ip=$(roscat sr_ur_arm_config $arm | grep robot_ip_address | sed -r 's/robot_ip_address: //g')
  echo "Checking arm: $arm_ip"
  check_firmware_from_ip $arm_ip
done

